### ISSUE TITLE
Missing prefs directory

### ISSUE THREAD

**Issue by ZachGray** [nxt-dev/nxt_editor#100]
Manually deleted preferences, subsequent launches throw errors.

C:\Users\user\Documents\nxt\prefs

Should remake the files

```
Traceback (most recent call last):
  File "C:\Users\Zach Gray\Documents\maya\2020\apps\nxt_maya\scripts\nxt_editor\main_window.py", line 803, in closeEvent
    user_dir.editor_cache[state_key] = self.saveState()
  File "C:\Users\Zach Gray\Documents\maya\2020\apps\nxt_maya\scripts\nxt_editor\user_dir.py", line 136, in __setitem__
    self.write()
  File "C:\Users\Zach Gray\Documents\maya\2020\apps\nxt_maya\scripts\nxt_editor\user_dir.py", line 194, in write
    with open(self.path, 'wb+') as fp:
IOError: [Errno 2] No such file or directory: 'C:/Users/Zach Gray/Documents\\nxt\\prefs\\3\\editor_cache'
```

**Comment by ImLucasBrown** [comment]
Can you provide the nxt version numbers as well as the python interpreter version?
ie `nxt maya Editor v1.2.3 API v0.4.0` - `Python 2.7`

I've had troubles with python 3 not playing right with pref files.
