### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by suekieza** [nxt-dev/nxt_editor#116]
**Describe the bug**
Weird issue: Traceback (most recent call last):
  File "c:\users\suesa\appdata\local\programs\python\python37\lib\site-packages\nxt_editor\dockwidgets\property_editor.py", line 1469, in mouseMoveEvent
    token = tokens.make_token_str(attr_name)
  File "c:\users\suesa\appdata\local\programs\python\python37\lib\site-packages\nxt\tokens.py", line 59, in make_token_str
    return TOKEN_PREFIX + token_content + TOKEN_SUFFIX
TypeError: can only concatenate str (not "NoneType") to str
keeps popping up had to end task nxt

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10,]

**Comment by ImLucasBrown** [comment]
Closing here. It is an core bug. See https://github.com/nxt-dev/nxt/issues/43
