### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by macross27** [nxt-dev/nxt_editor#214]
I am using Korean version of MS Windows. I ran into these errors below during pip installation of nxt-editor and nxt-core. Can you give me a suggestion what to do from here. Thanks!
```
WARNING: Discarding https://files.pythonhosted.org/packages/e6/dc/ddefbaab60eebac6f07ba829d3fab17e8c63bb1f1a430db460310cee835a/nxt-core-0.9.0.tar.gz#sha256=ffddc1c8e2ef91ef91798f1af3dd97016157a1d0f21af72e63547664b40a38f4 (from https://pypi.org/simple/nxt-core/) (requires-python:>=2.7, <=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading nxt-core-0.8.1.tar.gz (113 kB)
     |████████████████████████████████| 113 kB ...
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python3.7\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sdy\\AppData\\Local\\Temp\\pip-install-j2ouzmjw\\nxt-core_06646bab1d4b4e42bef60d0c391e02fa\\setup.py'"'"'; __file__='"'"'C:\\Users\\sdy\\AppData\\Local\\Temp\\pip-install-j2ouzmjw\\nxt-core_06646bab1d4b4e42bef60d0c391e02fa\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sdy\AppData\Local\Temp\pip-pip-egg-info-7d2krttg'
       cwd: C:\Users\sdy\AppData\Local\Temp\pip-install-j2ouzmjw\nxt-core_06646bab1d4b4e42bef60d0c391e02fa\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\sdy\AppData\Local\Temp\pip-install-j2ouzmjw\nxt-core_06646bab1d4b4e42bef60d0c391e02fa\setup.py", line 5, in <module>
      long_description = fh.read()
  UnicodeDecodeError: 'cp949' codec can't decode byte 0xc9 in position 24: illegal multibyte sequence
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/dd/4f/c332f59f1e2e03347833a09d2e83fdd8be7327671b10f2f2b7213042541f/nxt-core-0.8.1.tar.gz#sha256=dc555f6c29d0e78e6d95d0500d3b8bdd5ebe355e91287a5c91cc61bebf0e95a4 (from https://pypi.org/simple/nxt-core/) (requires-python:>=2.7, <=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading nxt-core-0.8.0.tar.gz (113 kB)
     |████████████████████████████████| 113 kB 6.4 MB/s
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python3.7\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sdy\\AppData\\Local\\Temp\\pip-install-j2ouzmjw\\nxt-core_56762fc9cdc14c6e822406c9c665420f\\setup.py'"'"'; __file__='"'"'C:\\Users\\sdy\\AppData\\Local\\Temp\\pip-install-j2ouzmjw\\nxt-core_56762fc9cdc14c6e822406c9c665420f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sdy\AppData\Local\Temp\pip-pip-egg-info-ih42qhnk'
       cwd: C:\Users\sdy\AppData\Local\Temp\pip-install-j2ouzmjw\nxt-core_56762fc9cdc14c6e822406c9c665420f\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\sdy\AppData\Local\Temp\pip-install-j2ouzmjw\nxt-core_56762fc9cdc14c6e822406c9c665420f\setup.py", line 5, in <module>
      long_description = fh.read()
  UnicodeDecodeError: 'cp949' codec can't decode byte 0xc9 in position 24: illegal multibyte sequence
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7b/77/176f2eb040598c93abf98cbe9aac3e64c8d9f1d574e18e4b6ff541e18463/nxt-core-0.8.0.tar.gz#sha256=21c5957df6130e851125bcb0ef5191a0cc1a603296c901b5d6329c33863a43ce (from https://pypi.org/simple/nxt-core/) (requires-python:>=2.7, <=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement nxt-core (from versions: 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.11.0, 0.12.0)
ERROR: No matching distribution found for nxt-core
```
(_edited for visual clarity_)

**Comment by macross27** [comment]
btw, I manually update the source codes, changing all read methods to something like this below

original:
with open(os.path.join(this_dir, "README.md"), "r") as fp:
    long_description = fp.read()


updated:
with open(os.path.join(this_dir, "README.md"), "r",encoding='UTF-8') as fp:
    long_description = fp.read()
